### ISSUE TITLE
Allow to add github actions

### ISSUE THREAD

**Issue by maroba** [maroba/manati#7]
As a first feature towards github actions, implement a command

```
manati add github-action
```

which creates a `.github/workflows` folder in the current project including a yml-file, equivalent to that in the `manti/.github/workflows` directory with appropriate settings. 

There should probably be a few options:

```
-n/--name (name of the action)
-b/--branches (upon push to what branch)
-p/--python-versions (which Python versions to test with)
-o/--os (which operating systems to test with, should be a Choice)
```

**Comment by manishankarconnect** [comment]
What functionality to be added to github actions?. I can support on it

**Comment by maroba** [comment]
Sure, if you like you can work on this issue! I have added some description. Any comments or suggestions regarding the issue?
